# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/v1/password_recovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!models/v1/password_recovery.proto\x12\tmodels.v1"B\n\x15\x45mailPasswordRecovery\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04salt\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tB\nZ\x08./modelsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "models.v1.password_recovery_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\010./models"
    _globals["_EMAILPASSWORDRECOVERY"]._serialized_start = 48
    _globals["_EMAILPASSWORDRECOVERY"]._serialized_end = 114
# @@protoc_insertion_point(module_scope)
