image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy

variables:
  REMOTE_USER: "ubrato"
  REMOTE_HOST: "194.58.96.228"
  REMOTE_PATH: "/home/ubrato/ubrato"

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - cp $KNOWN_HOSTS ~/.ssh/known_hosts

dev-build:
  only:
    - dev
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - cp .env.prod .env
    - docker build --build-arg GIT_VERSION=$CI_COMMIT_SHORT_SHA --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

dev-deploy:
  only:
    - dev
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p 2048 "cd $REMOTE_PATH &&
      ./update-back.sh && git clone git@gitlab.com:ubrato/ubrato-back.git &&
      cd ubrato-back && cp .env.prod .env &&
      docker compose up -d"

prod-build:
  only:
    - main
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - cp .env.prod .env
    - docker build --build-arg GIT_VERSION=$CI_COMMIT_SHORT_SHA --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

prod-deploy:
  only:
    - main
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p 2048 "cd $REMOTE_PATH &&
      ./update-back.sh && git clone git@gitlab.com:ubrato/ubrato-back.git &&
      cd ubrato-back && cp .env.prod .env &&
      docker compose up -d"