stages:
  - deploy

variables:
  REMOTE_USER: "ubrato"
  REMOTE_HOST: "185.103.102.159"
  REMOTE_PATH: "/home/ubrato/ubrato"

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - cp $KNOWN_HOSTS ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p 2048 "cd $REMOTE_PATH &&
      ./clean.sh && git clone git@gitlab.com:ubrato/ubrato-back.git &&
      cd ubrato-back && cp .env.prod .env &&
      docker build --build-arg GIT_VERSION=$CI_COMMIT_SHORT_SHA -t ubrato:latest . &&
      docker compose up -d"
