image: docker:latest
services:
  - docker:dind
stages:
  - lint
  - build
  - deploy

variables:
  REMOTE_USER: "ubrato"
  REMOTE_HOST: "194.58.96.228"
  REMOTE_PORT: "2022"
  REMOTE_PATH: "/home/ubrato/ubrato"

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - cp $KNOWN_HOSTS ~/.ssh/known_hosts

lint:
  image: python:3.11.6-slim-bullseye
  stage: lint
  script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    - mypy app/
    - pip install ruff 
    - ruff check --output-format=gitlab app/

prod-build:
  only:
    - main
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - cp .env.prod .env
    - docker build --build-arg GIT_VERSION=$CI_COMMIT_SHORT_SHA --pull -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"

prod-deploy:
  only:
    - main
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT "cd $REMOTE_PATH &&
      ./update-back.sh && git clone git@git.ubrato.ru:ubrato/ubrato-back.git &&
      cd ubrato-back && cp .env.prod .env && docker compose up -d"