FROM python:3.11.6-alpine3.18

ARG SERVER_PORT=3000
ARG SERVER_ADDR=0.0.0.0
ARG GIT_VERSION
ARG DB_DSN
ARG JWT_SECRET
ARG JWT_TTL=20
ARG SESSION_TTL=336
ARG DADATA_TOKEN
ARG REDIS_HOST
ARG REDIS_PASSWORD
ARG NATS_HOST

ENV SERVER_PORT=${SERVER_PORT}
ENV SERVER_ADDR=${SERVER_ADDR}
ENV GIT_VERSION=${GIT_VERSION}
ENV DB_DSN=${DB_DSN}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_TTL=${JWT_TTL}
ENV SESSION_TTL=${SESSION_TTL}
ENV DADATA_TOKEN=${DADATA_TOKEN}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV NATS_HOST=${NATS_HOST}

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100


RUN pip install poetry

WORKDIR /ubrato
COPY poetry.lock pyproject.toml /ubrato/

COPY ./app /ubrato/app
COPY ./scripts /ubrato/scripts

RUN poetry lock

RUN poetry install

EXPOSE $SERVER_PORT

HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://0.0.0.0:${SERVER_PORT}/health/ || exit 1

WORKDIR /ubrato/app

ENTRYPOINT [ "poetry", "run", "uvicorn", "main:app" ]