version: '3.8'
networks:
  ubrato:
    driver: bridge

services:
  api:
    container_name: ubrato-api
    image: registry.gitlab.com/ubrato/ubrato-back:latest
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - ubrato
    depends_on:
      - db
    restart: "on-failure"

  db:
    container_name: ubrato-db
    image: postgres
    expose:
      - "5432"
    volumes:
      - "./app/repositories/migration/000001_init_mg.up.sql:/docker-entrypoint-initdb.d/database.sql"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "postgres"
    networks: 
     - ubrato
    restart: "on-failure"