version: '3.8'
networks:
  test-backend:
    driver: bridge

services:
  db:
    image: postgres
    container_name: test-db
    ports:
      - "35432:5432"
    volumes:
      - "./app/repositories/migration/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "test"
    networks:
      - test-backend

    restart: "on-failure"