[errors]
error_while_create_user = "Internal error when creating a user"
user_email_not_found = "User with email {} not found."
user_not_found = "User not found."
session_expired = "Session expired"
no_barrier_token = "No barrier token"
invalid_barrier = "Bearer token is invalid"
invalid_services_count = "Tender cannot be without services"
invalid_objects_count = "Tender cannot be without objects"
expired_reset_code = "This reset code has expired"
no_access = "You don't have access"
already_has_offer = "User has already received an offer"
invalid_credential = "Invalid credentials"
user_already_exist = "User already exist"
tender_not_found = "Tender not found"
invalid_inn = "Invalid inn"
no_cookie = "Session cookie not found"
session_not_found = "Session not found."
org_not_found = "Organization not found."
userid_not_found = "User with ID {} not found."
tenderid_not_found = "Tender with ID {} not found."
data_already_exist = "Such data has already been registered."
city_not_fount = "City with id {} not found."
service_not_found = "Service with id {} not found."
questionnaire_not_found = "Questionnaire not found."
document_not_found = "Document with ID {} not found."
verified_request_not_found = "Verified request with ID {} not found."
cv_not_found = "CV with ID {} not found."
profile_not_found = "Profile org with ID {} not found."
no_draft_tender = "You don't have a draft version of the tender."

[notice]
end_of_registration.header = "Завершите регистрацию"
end_of_registration.text = "Для завершения регистрации подтвердите e-mail"

pass_verfication.header = "Верификация пройдена"
pass_verfication.text = "Верификация пройдена, теперь можно совершать действия"

not_pass_verfication.header = "Верификация не пройдена"
not_pass_verfication.text = "Верификация не пройдена. Причина {}"

tender_not_pass_verfication.header = "Верификация не пройдена"
tender_not_pass_verfication.text = "Тендер не прошел модерацию. Внесите исправления"

tender_pass_verfication.header = "Верификация не пройдена"
tender_pass_verfication.text = "Модерация пройдена, прием откликов начнется {}"
tender_pass_verfication.href.text = "Открыть тендер"
tender_pass_verfication.href.link = "/tenders/{}"

